language: java
jdk:
 - openjdk11
dist: trusty
addons:
  sonarcloud:
    organization: "gianmarcomerletti"
    token: "789231355e597c937a9163f5a3fc2892641d0132"
script:
  -  mvn clean verify
  - sonar-scanner